CREATE TABLE IF NOT EXISTS `admin_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `user_name` varchar(20) NOT NULL DEFAULT '' COMMENT '用户账户',
  `action` varchar(100) NOT NULL DEFAULT '0' COMMENT '动作名称',
  `route` varchar(255) NOT NULL DEFAULT '' COMMENT '路由名称',
  `method` varchar(255) NOT NULL DEFAULT '' COMMENT '模块/类/方法',
  `describe` varchar(255) NOT NULL DEFAULT '' COMMENT '描述',
  `data` text COMMENT '操作数据',
  `ip` varchar(64) NOT NULL DEFAULT '' COMMENT 'IP地址',
  `ipaddr` varchar(100) NOT NULL DEFAULT '' COMMENT 'ip地区信息',
  `trace_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'trace id',
  `span_id` varchar(32) NOT NULL DEFAULT '' COMMENT 'span id',
  `http_status` int NOT NULL DEFAULT '200' COMMENT 'http状态码',
  `biz_code` int NOT NULL DEFAULT '0' COMMENT '业务码',
  `latency_ms` bigint NOT NULL DEFAULT '0' COMMENT '请求耗时ms',
  `success` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否成功',
  `error_message` varchar(500) NOT NULL DEFAULT '' COMMENT '错误信息',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_action` (`action`),
  KEY `idx_user_name` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='管理员操作日志';
