CREATE TABLE IF NOT EXISTS `admin_message` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `type` varchar(64) NOT NULL DEFAULT '' COMMENT '消息类型',
  `level` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '消息等级：1info 2warning 3error',
  `title` varchar(200) NOT NULL DEFAULT '' COMMENT '消息标题',
  `content` text COMMENT '消息内容',
  `data` text COMMENT '扩展数据JSON',
  `link` varchar(500) NOT NULL DEFAULT '' COMMENT '跳转链接(路由或外链)',
  `sender_admin_id` int unsigned NOT NULL DEFAULT '0' COMMENT '发送人管理员ID',
  `sender_admin_name` varchar(20) NOT NULL DEFAULT '' COMMENT '发送人账号快照',
  `reply_to_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '回复的原消息ID',
  `handled_status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '处理状态(0未处理1已处理)',
  `handled_by_admin_id` int unsigned NOT NULL DEFAULT '0' COMMENT '处理人管理员ID',
  `handled_by_admin_name` varchar(20) NOT NULL DEFAULT '' COMMENT '处理人账号快照',
  `handled_at` datetime NULL DEFAULT NULL COMMENT '处理时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_type` (`type`),
  KEY `idx_level` (`level`),
  KEY `idx_sender_admin_id` (`sender_admin_id`),
  KEY `idx_handled_status` (`handled_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='管理员消息主表';
