-- 用途：归档任务运行配置草稿表。

CREATE TABLE IF NOT EXISTS `runtime_archive_job` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(128) NOT NULL COMMENT '归档任务名称',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `database_name` varchar(64) NOT NULL DEFAULT 'main' COMMENT '热表数据库',
  `table_name` varchar(128) NOT NULL DEFAULT '' COMMENT '热表名',
  `time_column` varchar(64) NOT NULL DEFAULT '' COMMENT '归档时间列',
  `time_column_type` varchar(32) NOT NULL DEFAULT '' COMMENT '时间列类型',
  `time_column_format` varchar(64) NOT NULL DEFAULT '' COMMENT '字符串时间格式',
  `time_column_unix_unit` varchar(32) NOT NULL DEFAULT '' COMMENT 'Unix时间单位',
  `primary_key` varchar(64) NOT NULL DEFAULT '' COMMENT '主键列',
  `archive_condition` varchar(500) NOT NULL DEFAULT '' COMMENT '归档过滤条件',
  `delete_condition` varchar(500) NOT NULL DEFAULT '' COMMENT '清理过滤条件',
  `split_unit` varchar(32) NOT NULL DEFAULT '' COMMENT '历史表拆分粒度',
  `custom_days` int NOT NULL DEFAULT '0' COMMENT '自定义分段天数',
  `hot_keep_days` int NOT NULL DEFAULT '0' COMMENT '热表保留天数',
  `archive_delay_days` int NOT NULL DEFAULT '0' COMMENT '归档延迟天数',
  `archive_window_seconds` int NOT NULL DEFAULT '0' COMMENT '归档窗口秒数',
  `archive_window_mode` varchar(32) NOT NULL DEFAULT '' COMMENT '归档窗口模式',
  `archive_max_windows_per_run` int NOT NULL DEFAULT '0' COMMENT '单次最大归档窗口数',
  `archive_auto_max_windows` int NOT NULL DEFAULT '0' COMMENT 'auto最大追赶窗口数',
  `archive_auto_light_rows` int NOT NULL DEFAULT '0' COMMENT 'auto轻量行数阈值',
  `archive_auto_light_ms` int NOT NULL DEFAULT '0' COMMENT 'auto轻量耗时阈值毫秒',
  `delete_disabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否禁用删除',
  `delete_delay_days` int NOT NULL DEFAULT '0' COMMENT '删除延迟天数',
  `delete_window_seconds` int NOT NULL DEFAULT '0' COMMENT '删除窗口秒数',
  `delete_max_windows_per_run` int NOT NULL DEFAULT '0' COMMENT '单次最大删除窗口数',
  `batch_size` int NOT NULL DEFAULT '0' COMMENT '归档批次大小',
  `delete_batch_size` int NOT NULL DEFAULT '0' COMMENT '删除批次大小',
  `max_history_tables` int NOT NULL DEFAULT '0' COMMENT '最大历史表数量',
  `history_table_prefix` varchar(128) NOT NULL DEFAULT '' COMMENT '历史表前缀',
  `history_table_name_rule` varchar(255) NOT NULL DEFAULT '' COMMENT '历史表命名规则',
  `start_at` varchar(64) NOT NULL DEFAULT '' COMMENT '首次归档起点',
  `query_write_db` tinyint(1) NOT NULL DEFAULT '0' COMMENT '查询是否强制走主库',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序值',
  `remark` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `created_by_admin_id` int unsigned NOT NULL DEFAULT '0' COMMENT '创建管理员ID',
  `updated_by_admin_id` int unsigned NOT NULL DEFAULT '0' COMMENT '更新管理员ID',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_name` (`name`),
  KEY `idx_archive_table` (`database_name`,`table_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='归档任务运行配置草稿';

INSERT IGNORE INTO `runtime_archive_job` (`id`, `name`, `enabled`, `database_name`, `table_name`, `time_column`, `time_column_type`, `time_column_format`, `time_column_unix_unit`, `primary_key`, `archive_condition`, `delete_condition`, `split_unit`, `custom_days`, `hot_keep_days`, `archive_delay_days`, `archive_window_seconds`, `archive_window_mode`, `archive_max_windows_per_run`, `archive_auto_max_windows`, `archive_auto_light_rows`, `archive_auto_light_ms`, `delete_disabled`, `delete_delay_days`, `delete_window_seconds`, `delete_max_windows_per_run`, `batch_size`, `delete_batch_size`, `max_history_tables`, `history_table_prefix`, `history_table_name_rule`, `start_at`, `query_write_db`, `sort_order`, `remark`, `created_by_admin_id`, `updated_by_admin_id`, `created_at`, `updated_at`) VALUES (1, 'admin_log', 1, 'main', 'admin_log', '', '', '', '', '', '', '', '', 0, 32, 2, 3600, 'auto', 2, 200, 20000, 3000, 0, 32, 0, 2, 3000, 1000, 12, '', '', '', 0, 1, '', 0, 0, '2026-06-16 00:00:00', '2026-06-16 00:00:00');
