CREATE TABLE IF NOT EXISTS `task_workflow_run` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `app_id` varchar(64) NOT NULL COMMENT '应用ID',
  `event_id` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '终态事件幂等键',
  `workflow_id` varchar(128) NOT NULL COMMENT '工作流实例ID',
  `workflow_name` varchar(128) NOT NULL COMMENT '工作流名称',
  `periodic_name` varchar(128) NOT NULL DEFAULT '' COMMENT '周期任务名称',
  `source` varchar(32) NOT NULL DEFAULT '' COMMENT '触发来源',
  `queue` varchar(128) NOT NULL DEFAULT '' COMMENT '默认队列',
  `status` varchar(16) NOT NULL COMMENT '工作流终态',
  `node_total` int unsigned NOT NULL DEFAULT 0 COMMENT '节点数量',
  `task_total` int unsigned NOT NULL DEFAULT 0 COMMENT '节点实例总量',
  `succeeded` int unsigned NOT NULL DEFAULT 0 COMMENT '成功节点实例数',
  `failed` int unsigned NOT NULL DEFAULT 0 COMMENT '失败节点实例数',
  `skipped` int unsigned NOT NULL DEFAULT 0 COMMENT '跳过节点实例数',
  `trace_total` bigint NOT NULL DEFAULT 0 COMMENT '处理总量',
  `trace_read` bigint NOT NULL DEFAULT 0 COMMENT '读取数量',
  `trace_write` bigint NOT NULL DEFAULT 0 COMMENT '写入数量',
  `trace_delete` bigint NOT NULL DEFAULT 0 COMMENT '删除数量',
  `trace_error` bigint NOT NULL DEFAULT 0 COMMENT '处理错误量',
  `duration_ms` bigint unsigned NOT NULL DEFAULT 0 COMMENT '工作流耗时毫秒',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败摘要',
  `snapshot_json` json NOT NULL COMMENT '有界自适应历史快照JSON',
  `workflow_created_at` datetime(3) NOT NULL COMMENT '工作流创建时间',
  `finished_at` datetime(3) NOT NULL COMMENT '终态时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '落库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_event` (`app_id`,`event_id`),
  KEY `idx_app_finished` (`app_id`,`finished_at`,`id`),
  KEY `idx_app_workflow` (`app_id`,`workflow_id`,`finished_at`),
  KEY `idx_app_name_finished` (`app_id`,`workflow_name`,`finished_at`),
  KEY `idx_app_periodic_finished` (`app_id`,`periodic_name`,`finished_at`),
  KEY `idx_app_status_finished` (`app_id`,`status`,`finished_at`),
  KEY `idx_app_source_finished` (`app_id`,`source`,`finished_at`),
  KEY `idx_app_queue_finished` (`app_id`,`queue`,`finished_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务工作流终态汇总';
