CREATE TABLE IF NOT EXISTS `task_failure` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `app_id` varchar(64) NOT NULL COMMENT '应用ID',
  `event_id` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '失败事件幂等键',
  `task_id` varchar(128) NOT NULL COMMENT 'Asynq任务ID',
  `task_type` varchar(128) NOT NULL DEFAULT '' COMMENT '任务类型',
  `task_name` varchar(128) NOT NULL DEFAULT '' COMMENT '任务展示名',
  `queue` varchar(128) NOT NULL DEFAULT '' COMMENT '所属队列',
  `source` varchar(32) NOT NULL DEFAULT '' COMMENT '触发来源',
  `periodic_name` varchar(128) NOT NULL DEFAULT '' COMMENT '周期任务名称',
  `workflow_id` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流实例ID',
  `workflow_name` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流名称',
  `workflow_node` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流节点',
  `retried` int unsigned NOT NULL DEFAULT 0 COMMENT '已重试次数',
  `max_retry` int unsigned NOT NULL DEFAULT 0 COMMENT '最大重试次数',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败摘要',
  `trace_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `failed_at` datetime(3) NOT NULL COMMENT '失败时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '落库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_event` (`app_id`,`event_id`),
  KEY `idx_app_failed` (`app_id`,`failed_at`,`id`),
  KEY `idx_app_task` (`app_id`,`task_id`,`failed_at`),
  KEY `idx_app_queue_failed` (`app_id`,`queue`,`failed_at`),
  KEY `idx_app_source_failed` (`app_id`,`source`,`failed_at`),
  KEY `idx_app_workflow_failed` (`app_id`,`workflow_id`,`failed_at`),
  KEY `idx_app_type_failed` (`app_id`,`task_type`,`failed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='任务终态失败明细';
