CREATE TABLE IF NOT EXISTS `task_run` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `app_id` varchar(64) NOT NULL COMMENT '应用ID',
  `event_id` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '终态事件幂等键',
  `task_id` varchar(128) NOT NULL COMMENT 'Asynq任务ID',
  `task_type` varchar(128) NOT NULL DEFAULT '' COMMENT '任务类型',
  `task_name` varchar(128) NOT NULL DEFAULT '' COMMENT '任务展示名',
  `queue` varchar(128) NOT NULL DEFAULT '' COMMENT '所属队列',
  `source` varchar(32) NOT NULL DEFAULT '' COMMENT '触发来源',
  `periodic_name` varchar(128) NOT NULL DEFAULT '' COMMENT '周期任务名称',
  `workflow_id` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流实例ID',
  `workflow_name` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流名称',
  `workflow_node` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流节点',
  `shard_index` int unsigned NOT NULL DEFAULT 0 COMMENT '工作流分片下标',
  `shard_total` int unsigned NOT NULL DEFAULT 0 COMMENT '工作流分片总数',
  `status` varchar(16) NOT NULL COMMENT '终态',
  `retried` int unsigned NOT NULL DEFAULT 0 COMMENT '已重试次数',
  `max_retry` int unsigned NOT NULL DEFAULT 0 COMMENT '最大重试次数',
  `trace_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `trace_total` bigint NOT NULL DEFAULT 0 COMMENT '处理总量',
  `trace_read` bigint NOT NULL DEFAULT 0 COMMENT '读取数量',
  `trace_write` bigint NOT NULL DEFAULT 0 COMMENT '写入数量',
  `trace_delete` bigint NOT NULL DEFAULT 0 COMMENT '删除数量',
  `trace_error` bigint NOT NULL DEFAULT 0 COMMENT '错误数量',
  `duration_ms` bigint unsigned NOT NULL DEFAULT 0 COMMENT '执行耗时毫秒',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败摘要',
  `snapshot_json` json NOT NULL COMMENT '有界终态快照JSON',
  `started_at` datetime(3) NOT NULL COMMENT '开始时间',
  `finished_at` datetime(3) NOT NULL COMMENT '终态时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '落库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_event` (`app_id`,`event_id`),
  KEY `idx_app_finished` (`app_id`,`finished_at`,`id`),
  KEY `idx_app_task` (`app_id`,`task_id`,`finished_at`),
  KEY `idx_app_name_finished` (`app_id`,`task_name`,`finished_at`),
  KEY `idx_app_type_finished` (`app_id`,`task_type`,`finished_at`),
  KEY `idx_app_queue_finished` (`app_id`,`queue`,`finished_at`),
  KEY `idx_app_status_finished` (`app_id`,`status`,`finished_at`),
  KEY `idx_app_periodic_finished` (`app_id`,`periodic_name`,`finished_at`),
  KEY `idx_app_workflow_finished` (`app_id`,`workflow_id`,`finished_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='全部任务短期终态摘要';
