package model

import "time"

const (
	// TableNameTaskWorkflowRun 是任务工作流终态汇总表名。
	TableNameTaskWorkflowRun = "task_workflow_run"
	// TableNameTaskFailure 是任务终态失败明细表名。
	TableNameTaskFailure = "task_failure"
)

// TaskWorkflowRun 保存一轮工作流终态汇总和固定容量的自适应明细。
type TaskWorkflowRun struct {
	ID                uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                                                                                                                                                                                                                                                                                                   // 主键 ID
	AppID             string    `gorm:"column:app_id;type:varchar(64);not null;uniqueIndex:uk_app_event,priority:1;index:idx_app_finished,priority:1;index:idx_app_workflow,priority:1;index:idx_app_name_finished,priority:1;index:idx_app_periodic_finished,priority:1;index:idx_app_status_finished,priority:1;index:idx_app_source_finished,priority:1;index:idx_app_queue_finished,priority:1" json:"appId"` // 应用命名空间
	EventID           string    `gorm:"column:event_id;type:char(64);not null;uniqueIndex:uk_app_event,priority:2" json:"eventId"`                                                                                                                                                                                                                                                                                // 固定长度终态事件幂等键
	WorkflowID        string    `gorm:"column:workflow_id;type:varchar(128);not null;index:idx_app_workflow,priority:2" json:"workflowId"`                                                                                                                                                                                                                                                                        // 工作流实例 ID
	WorkflowName      string    `gorm:"column:workflow_name;type:varchar(128);not null;index:idx_app_name_finished,priority:2" json:"workflowName"`                                                                                                                                                                                                                                                               // 工作流名称
	PeriodicName      string    `gorm:"column:periodic_name;type:varchar(128);not null;default:'';index:idx_app_periodic_finished,priority:2" json:"periodicName"`                                                                                                                                                                                                                                                // 周期任务名称
	Source            string    `gorm:"column:source;type:varchar(32);not null;default:'';index:idx_app_source_finished,priority:2" json:"source"`                                                                                                                                                                                                                                                                // 触发来源
	Queue             string    `gorm:"column:queue;type:varchar(128);not null;default:'';index:idx_app_queue_finished,priority:2" json:"queue"`                                                                                                                                                                                                                                                                  // 默认队列
	Status            string    `gorm:"column:status;type:varchar(16);not null;index:idx_app_status_finished,priority:2" json:"status"`                                                                                                                                                                                                                                                                           // 工作流终态
	NodeTotal         int       `gorm:"column:node_total;type:int unsigned;not null;default:0" json:"nodeTotal"`                                                                                                                                                                                                                                                                                                  // 节点数量
	TaskTotal         int       `gorm:"column:task_total;type:int unsigned;not null;default:0" json:"taskTotal"`                                                                                                                                                                                                                                                                                                  // 节点实例总量
	Succeeded         int       `gorm:"column:succeeded;type:int unsigned;not null;default:0" json:"succeeded"`                                                                                                                                                                                                                                                                                                   // 成功节点实例数
	Failed            int       `gorm:"column:failed;type:int unsigned;not null;default:0" json:"failed"`                                                                                                                                                                                                                                                                                                         // 失败节点实例数
	Skipped           int       `gorm:"column:skipped;type:int unsigned;not null;default:0" json:"skipped"`                                                                                                                                                                                                                                                                                                       // 跳过节点实例数
	TraceTotal        int64     `gorm:"column:trace_total;type:bigint;not null;default:0" json:"traceTotal"`                                                                                                                                                                                                                                                                                                      // 处理总量
	TraceRead         int64     `gorm:"column:trace_read;type:bigint;not null;default:0" json:"traceRead"`                                                                                                                                                                                                                                                                                                        // 读取数量
	TraceWrite        int64     `gorm:"column:trace_write;type:bigint;not null;default:0" json:"traceWrite"`                                                                                                                                                                                                                                                                                                      // 写入数量
	TraceDelete       int64     `gorm:"column:trace_delete;type:bigint;not null;default:0" json:"traceDelete"`                                                                                                                                                                                                                                                                                                    // 删除数量
	TraceError        int64     `gorm:"column:trace_error;type:bigint;not null;default:0" json:"traceError"`                                                                                                                                                                                                                                                                                                      // 处理错误量
	DurationMS        int64     `gorm:"column:duration_ms;type:bigint unsigned;not null;default:0" json:"durationMs"`                                                                                                                                                                                                                                                                                             // 工作流耗时毫秒
	ErrorMessage      string    `gorm:"column:error_message;type:varchar(1000);not null;default:''" json:"errorMessage"`                                                                                                                                                                                                                                                                                          // 失败摘要
	SnapshotJSON      string    `gorm:"column:snapshot_json;type:json;not null" json:"snapshotJson"`                                                                                                                                                                                                                                                                                                              // 固定容量的自适应历史快照
	WorkflowCreatedAt time.Time `gorm:"column:workflow_created_at;type:datetime(3);not null" json:"workflowCreatedAt"`                                                                                                                                                                                                                                                                                            // 工作流创建时间
	FinishedAt        time.Time `gorm:"column:finished_at;type:datetime(3);not null;index:idx_app_finished,priority:2;index:idx_app_workflow,priority:3;index:idx_app_name_finished,priority:3;index:idx_app_periodic_finished,priority:3;index:idx_app_status_finished,priority:3;index:idx_app_source_finished,priority:3;index:idx_app_queue_finished,priority:3" json:"finishedAt"`                           // 终态时间
	CreatedAt         time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`                                                                                                                                                                                                                                                                                // 落库时间
}

// TableName 返回任务工作流终态汇总表名。
func (*TaskWorkflowRun) TableName() string { return TableNameTaskWorkflowRun }

// TaskFailure 保存最终失败任务的最小排障信息，不保存原始业务载荷。
type TaskFailure struct {
	ID           uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                                                                                                                                                                                                                                            // 主键 ID
	AppID        string    `gorm:"column:app_id;type:varchar(64);not null;uniqueIndex:uk_app_event,priority:1;index:idx_app_failed,priority:1;index:idx_app_task,priority:1;index:idx_app_queue_failed,priority:1;index:idx_app_source_failed,priority:1;index:idx_app_workflow_failed,priority:1;index:idx_app_type_failed,priority:1" json:"appId"` // 应用命名空间
	EventID      string    `gorm:"column:event_id;type:char(64);not null;uniqueIndex:uk_app_event,priority:2" json:"eventId"`                                                                                                                                                                                                                         // 固定长度失败事件幂等键
	TaskID       string    `gorm:"column:task_id;type:varchar(128);not null;index:idx_app_task,priority:2" json:"taskId"`                                                                                                                                                                                                                             // Asynq 任务 ID
	TaskType     string    `gorm:"column:task_type;type:varchar(128);not null;default:'';index:idx_app_type_failed,priority:2" json:"taskType"`                                                                                                                                                                                                       // 任务类型
	TaskName     string    `gorm:"column:task_name;type:varchar(128);not null;default:''" json:"taskName"`                                                                                                                                                                                                                                            // 任务展示名
	Queue        string    `gorm:"column:queue;type:varchar(128);not null;default:'';index:idx_app_queue_failed,priority:2" json:"queue"`                                                                                                                                                                                                             // 所属队列
	Source       string    `gorm:"column:source;type:varchar(32);not null;default:'';index:idx_app_source_failed,priority:2" json:"source"`                                                                                                                                                                                                           // 触发来源
	PeriodicName string    `gorm:"column:periodic_name;type:varchar(128);not null;default:''" json:"periodicName"`                                                                                                                                                                                                                                    // 周期任务名称
	WorkflowID   string    `gorm:"column:workflow_id;type:varchar(128);not null;default:'';index:idx_app_workflow_failed,priority:2" json:"workflowId"`                                                                                                                                                                                               // 工作流实例 ID
	WorkflowName string    `gorm:"column:workflow_name;type:varchar(128);not null;default:''" json:"workflowName"`                                                                                                                                                                                                                                    // 工作流名称
	WorkflowNode string    `gorm:"column:workflow_node;type:varchar(128);not null;default:''" json:"workflowNode"`                                                                                                                                                                                                                                    // 工作流节点
	Retried      int       `gorm:"column:retried;type:int unsigned;not null;default:0" json:"retried"`                                                                                                                                                                                                                                                // 已重试次数
	MaxRetry     int       `gorm:"column:max_retry;type:int unsigned;not null;default:0" json:"maxRetry"`                                                                                                                                                                                                                                             // 最大重试次数
	ErrorMessage string    `gorm:"column:error_message;type:varchar(1000);not null;default:''" json:"errorMessage"`                                                                                                                                                                                                                                   // 脱敏失败摘要
	TraceID      string    `gorm:"column:trace_id;type:varchar(64);not null;default:''" json:"traceId"`                                                                                                                                                                                                                                               // 链路追踪 ID
	FailedAt     time.Time `gorm:"column:failed_at;type:datetime(3);not null;index:idx_app_failed,priority:2;index:idx_app_task,priority:3;index:idx_app_queue_failed,priority:3;index:idx_app_workflow_failed,priority:3;index:idx_app_source_failed,priority:3;index:idx_app_type_failed,priority:3" json:"failedAt"`                               // 失败时间
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`                                                                                                                                                                                                                         // 落库时间
}

// TableName 返回任务终态失败明细表名。
func (*TaskFailure) TableName() string { return TableNameTaskFailure }
